minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: false
  sharp: false
  simple-git-hooks: false
  workerd: false
minimumReleaseAgeExclude:
  - "@cloudflare/vitest-plugin@1.4.0"
  - miniflare@5.20261006.1-alpha
  - wrangler@4.149.0
